/* 
 * Quickpay API v10
 *
 * <h2 id=\"authorization\">Authorization</h2>  <p>Authorization is done using basic-auth. Authorization can be done with a user or an agreement.</p>  <ul>   <li>When authorized with a user one is able to edit own settings, create new merchant or request access to existing merchant.</li>   <li>When authorized with an agreement one is able to perform anything on the account that agreement gives permissions to.</li> </ul>  
 *
 * OpenAPI spec version: 10.0
 * Contact: support@quickpay.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AclPermission
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AclPermissionTests
    {
        // TODO uncomment below to declare an instance variable for AclPermission
        //private AclPermission instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AclPermission
            //instance = new AclPermission();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AclPermission
        /// </summary>
        [Test]
        public void AclPermissionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AclPermission
            //Assert.IsInstanceOfType<AclPermission> (instance, "variable 'instance' is a AclPermission");
        }


        /// <summary>
        /// Test the property 'Delete'
        /// </summary>
        [Test]
        public void DeleteTest()
        {
            // TODO unit test for the property 'Delete'
        }
        /// <summary>
        /// Test the property 'Get'
        /// </summary>
        [Test]
        public void GetTest()
        {
            // TODO unit test for the property 'Get'
        }
        /// <summary>
        /// Test the property 'Patch'
        /// </summary>
        [Test]
        public void PatchTest()
        {
            // TODO unit test for the property 'Patch'
        }
        /// <summary>
        /// Test the property 'Post'
        /// </summary>
        [Test]
        public void PostTest()
        {
            // TODO unit test for the property 'Post'
        }
        /// <summary>
        /// Test the property 'Put'
        /// </summary>
        [Test]
        public void PutTest()
        {
            // TODO unit test for the property 'Put'
        }
        /// <summary>
        /// Test the property 'Resource'
        /// </summary>
        [Test]
        public void ResourceTest()
        {
            // TODO unit test for the property 'Resource'
        }

    }

}
