/* 
 * Quickpay API v10
 *
 * <h2 id=\"authorization\">Authorization</h2>  Authorization is done using basic-auth. Authorization can be done with a user or an agreement.  <ul>   <li>When authorized with a user one is able to edit own settings, create new merchant or request access to existing merchant.</li>   <li>When authorized with an agreement one is able to perform anything on the account that agreement gives permissions to.</li> </ul>  
 *
 * OpenAPI spec version: 10.0
 * Contact: support@quickpay.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AcquirerSettingsSwedbank
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AcquirerSettingsSwedbankTests
    {
        // TODO uncomment below to declare an instance variable for AcquirerSettingsSwedbank
        //private AcquirerSettingsSwedbank instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AcquirerSettingsSwedbank
            //instance = new AcquirerSettingsSwedbank();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AcquirerSettingsSwedbank
        /// </summary>
        [Test]
        public void AcquirerSettingsSwedbankInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AcquirerSettingsSwedbank
            //Assert.IsInstanceOfType<AcquirerSettingsSwedbank> (instance, "variable 'instance' is a AcquirerSettingsSwedbank");
        }


        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Test]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }
        /// <summary>
        /// Test the property 'Americanexpress'
        /// </summary>
        [Test]
        public void AmericanexpressTest()
        {
            // TODO unit test for the property 'Americanexpress'
        }
        /// <summary>
        /// Test the property 'BusinessCode'
        /// </summary>
        [Test]
        public void BusinessCodeTest()
        {
            // TODO unit test for the property 'BusinessCode'
        }
        /// <summary>
        /// Test the property 'Dinersclub'
        /// </summary>
        [Test]
        public void DinersclubTest()
        {
            // TODO unit test for the property 'Dinersclub'
        }
        /// <summary>
        /// Test the property 'IdentificationCode'
        /// </summary>
        [Test]
        public void IdentificationCodeTest()
        {
            // TODO unit test for the property 'IdentificationCode'
        }
        /// <summary>
        /// Test the property 'IdentificationCodeInt'
        /// </summary>
        [Test]
        public void IdentificationCodeIntTest()
        {
            // TODO unit test for the property 'IdentificationCodeInt'
        }
        /// <summary>
        /// Test the property 'MastercardBin'
        /// </summary>
        [Test]
        public void MastercardBinTest()
        {
            // TODO unit test for the property 'MastercardBin'
        }
        /// <summary>
        /// Test the property 'MastercardMpiMerchantId'
        /// </summary>
        [Test]
        public void MastercardMpiMerchantIdTest()
        {
            // TODO unit test for the property 'MastercardMpiMerchantId'
        }
        /// <summary>
        /// Test the property 'Recurring'
        /// </summary>
        [Test]
        public void RecurringTest()
        {
            // TODO unit test for the property 'Recurring'
        }
        /// <summary>
        /// Test the property 'Securepay'
        /// </summary>
        [Test]
        public void SecurepayTest()
        {
            // TODO unit test for the property 'Securepay'
        }
        /// <summary>
        /// Test the property 'VisaBin'
        /// </summary>
        [Test]
        public void VisaBinTest()
        {
            // TODO unit test for the property 'VisaBin'
        }
        /// <summary>
        /// Test the property 'VisaMpiMerchantId'
        /// </summary>
        [Test]
        public void VisaMpiMerchantIdTest()
        {
            // TODO unit test for the property 'VisaMpiMerchantId'
        }

    }

}
