/* 
 * Quickpay API v10
 *
 * <h2 id=\"authorization\">Authorization</h2>  Authorization is done using basic-auth. Authorization can be done with a user or an agreement.  <ul>   <li>When authorized with a user one is able to edit own settings, create new merchant or request access to existing merchant.</li>   <li>When authorized with an agreement one is able to perform anything on the account that agreement gives permissions to.</li> </ul>  
 *
 * OpenAPI spec version: 10.0
 * Contact: support@quickpay.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AcquirerSettingsVipps
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AcquirerSettingsVippsTests
    {
        // TODO uncomment below to declare an instance variable for AcquirerSettingsVipps
        //private AcquirerSettingsVipps instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AcquirerSettingsVipps
            //instance = new AcquirerSettingsVipps();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AcquirerSettingsVipps
        /// </summary>
        [Test]
        public void AcquirerSettingsVippsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AcquirerSettingsVipps
            //Assert.IsInstanceOfType<AcquirerSettingsVipps> (instance, "variable 'instance' is a AcquirerSettingsVipps");
        }


        /// <summary>
        /// Test the property 'AccessTokenSubscriptionKey'
        /// </summary>
        [Test]
        public void AccessTokenSubscriptionKeyTest()
        {
            // TODO unit test for the property 'AccessTokenSubscriptionKey'
        }
        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Test]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }
        /// <summary>
        /// Test the property 'ClientId'
        /// </summary>
        [Test]
        public void ClientIdTest()
        {
            // TODO unit test for the property 'ClientId'
        }
        /// <summary>
        /// Test the property 'ClientSecret'
        /// </summary>
        [Test]
        public void ClientSecretTest()
        {
            // TODO unit test for the property 'ClientSecret'
        }
        /// <summary>
        /// Test the property 'EcommerceSubscriptionKey'
        /// </summary>
        [Test]
        public void EcommerceSubscriptionKeyTest()
        {
            // TODO unit test for the property 'EcommerceSubscriptionKey'
        }
        /// <summary>
        /// Test the property 'Orgno'
        /// </summary>
        [Test]
        public void OrgnoTest()
        {
            // TODO unit test for the property 'Orgno'
        }
        /// <summary>
        /// Test the property 'SerialNumber'
        /// </summary>
        [Test]
        public void SerialNumberTest()
        {
            // TODO unit test for the property 'SerialNumber'
        }

    }

}
