/* 
 * Quickpay API v10
 *
 * <h2 id=\"authorization\">Authorization</h2>  <p>Authorization is done using basic-auth. Authorization can be done with a user or an agreement.</p>  <ul>   <li>When authorized with a user one is able to edit own settings, create new merchant or request access to existing merchant.</li>   <li>When authorized with an agreement one is able to perform anything on the account that agreement gives permissions to.</li> </ul>  
 *
 * OpenAPI spec version: 10.0
 * Contact: support@quickpay.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AcquirerSettingsMobilePaySubscriptions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AcquirerSettingsMobilePaySubscriptionsTests
    {
        // TODO uncomment below to declare an instance variable for AcquirerSettingsMobilePaySubscriptions
        //private AcquirerSettingsMobilePaySubscriptions instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AcquirerSettingsMobilePaySubscriptions
            //instance = new AcquirerSettingsMobilePaySubscriptions();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AcquirerSettingsMobilePaySubscriptions
        /// </summary>
        [Test]
        public void AcquirerSettingsMobilePaySubscriptionsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AcquirerSettingsMobilePaySubscriptions
            //Assert.IsInstanceOfType<AcquirerSettingsMobilePaySubscriptions> (instance, "variable 'instance' is a AcquirerSettingsMobilePaySubscriptions");
        }


        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Test]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }
        /// <summary>
        /// Test the property 'AuthState'
        /// </summary>
        [Test]
        public void AuthStateTest()
        {
            // TODO unit test for the property 'AuthState'
        }
        /// <summary>
        /// Test the property 'CodeVerifier'
        /// </summary>
        [Test]
        public void CodeVerifierTest()
        {
            // TODO unit test for the property 'CodeVerifier'
        }
        /// <summary>
        /// Test the property 'LastTokenRefresh'
        /// </summary>
        [Test]
        public void LastTokenRefreshTest()
        {
            // TODO unit test for the property 'LastTokenRefresh'
        }
        /// <summary>
        /// Test the property 'Nonce'
        /// </summary>
        [Test]
        public void NonceTest()
        {
            // TODO unit test for the property 'Nonce'
        }
        /// <summary>
        /// Test the property 'PendingStatus'
        /// </summary>
        [Test]
        public void PendingStatusTest()
        {
            // TODO unit test for the property 'PendingStatus'
        }
        /// <summary>
        /// Test the property 'Provider'
        /// </summary>
        [Test]
        public void ProviderTest()
        {
            // TODO unit test for the property 'Provider'
        }
        /// <summary>
        /// Test the property 'RefreshToken'
        /// </summary>
        [Test]
        public void RefreshTokenTest()
        {
            // TODO unit test for the property 'RefreshToken'
        }

    }

}
