/* 
 * Quickpay API v10
 *
 * <h2 id=\"authorization\">Authorization</h2>  <p>Authorization is done using basic-auth. Authorization can be done with a user or an agreement.</p>  <ul>   <li>When authorized with a user one is able to edit own settings, create new merchant or request access to existing merchant.</li>   <li>When authorized with an agreement one is able to perform anything on the account that agreement gives permissions to.</li> </ul>  
 *
 * OpenAPI spec version: 10.0
 * Contact: support@quickpay.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Activity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ActivityTests
    {
        // TODO uncomment below to declare an instance variable for Activity
        //private Activity instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Activity
            //instance = new Activity();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Activity
        /// </summary>
        [Test]
        public void ActivityInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Activity
            //Assert.IsInstanceOfType<Activity> (instance, "variable 'instance' is a Activity");
        }


        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Test]
        public void AccountIdTest()
        {
            // TODO unit test for the property 'AccountId'
        }
        /// <summary>
        /// Test the property 'Action'
        /// </summary>
        [Test]
        public void ActionTest()
        {
            // TODO unit test for the property 'Action'
        }
        /// <summary>
        /// Test the property 'Changes'
        /// </summary>
        [Test]
        public void ChangesTest()
        {
            // TODO unit test for the property 'Changes'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'Extra'
        /// </summary>
        [Test]
        public void ExtraTest()
        {
            // TODO unit test for the property 'Extra'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Support'
        /// </summary>
        [Test]
        public void SupportTest()
        {
            // TODO unit test for the property 'Support'
        }
        /// <summary>
        /// Test the property 'TargetId'
        /// </summary>
        [Test]
        public void TargetIdTest()
        {
            // TODO unit test for the property 'TargetId'
        }
        /// <summary>
        /// Test the property 'TargetType'
        /// </summary>
        [Test]
        public void TargetTypeTest()
        {
            // TODO unit test for the property 'TargetType'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Test]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }

    }

}
