/* 
 * Quickpay API v10
 *
 * <h2 id=\"authorization\">Authorization</h2>  Authorization is done using basic-auth. Authorization can be done with a user or an agreement.  <ul>   <li>When authorized with a user one is able to edit own settings, create new merchant or request access to existing merchant.</li>   <li>When authorized with an agreement one is able to perform anything on the account that agreement gives permissions to.</li> </ul>  
 *
 * OpenAPI spec version: 10.0
 * Contact: support@quickpay.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CardLink
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CardLinkTests
    {
        // TODO uncomment below to declare an instance variable for CardLink
        //private CardLink instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CardLink
            //instance = new CardLink();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CardLink
        /// </summary>
        [Test]
        public void CardLinkInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CardLink
            //Assert.IsInstanceOfType<CardLink> (instance, "variable 'instance' is a CardLink");
        }


        /// <summary>
        /// Test the property 'Acquirer'
        /// </summary>
        [Test]
        public void AcquirerTest()
        {
            // TODO unit test for the property 'Acquirer'
        }
        /// <summary>
        /// Test the property 'AgreementId'
        /// </summary>
        [Test]
        public void AgreementIdTest()
        {
            // TODO unit test for the property 'AgreementId'
        }
        /// <summary>
        /// Test the property 'BrandingConfig'
        /// </summary>
        [Test]
        public void BrandingConfigTest()
        {
            // TODO unit test for the property 'BrandingConfig'
        }
        /// <summary>
        /// Test the property 'BrandingId'
        /// </summary>
        [Test]
        public void BrandingIdTest()
        {
            // TODO unit test for the property 'BrandingId'
        }
        /// <summary>
        /// Test the property 'Callbackurl'
        /// </summary>
        [Test]
        public void CallbackurlTest()
        {
            // TODO unit test for the property 'Callbackurl'
        }
        /// <summary>
        /// Test the property 'Cancelurl'
        /// </summary>
        [Test]
        public void CancelurlTest()
        {
            // TODO unit test for the property 'Cancelurl'
        }
        /// <summary>
        /// Test the property 'Continueurl'
        /// </summary>
        [Test]
        public void ContinueurlTest()
        {
            // TODO unit test for the property 'Continueurl'
        }
        /// <summary>
        /// Test the property 'Framed'
        /// </summary>
        [Test]
        public void FramedTest()
        {
            // TODO unit test for the property 'Framed'
        }
        /// <summary>
        /// Test the property 'GoogleAnalyticsClientId'
        /// </summary>
        [Test]
        public void GoogleAnalyticsClientIdTest()
        {
            // TODO unit test for the property 'GoogleAnalyticsClientId'
        }
        /// <summary>
        /// Test the property 'GoogleAnalyticsTrackingId'
        /// </summary>
        [Test]
        public void GoogleAnalyticsTrackingIdTest()
        {
            // TODO unit test for the property 'GoogleAnalyticsTrackingId'
        }
        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Test]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }
        /// <summary>
        /// Test the property 'PaymentMethods'
        /// </summary>
        [Test]
        public void PaymentMethodsTest()
        {
            // TODO unit test for the property 'PaymentMethods'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }

    }

}
