/* 
 * Quickpay API v10
 *
 * <h2 id=\"authorization\">Authorization</h2>  <p>Authorization is done using basic-auth. Authorization can be done with a user or an agreement.</p>  <ul>   <li>When authorized with a user one is able to edit own settings, create new merchant or request access to existing merchant.</li>   <li>When authorized with an agreement one is able to perform anything on the account that agreement gives permissions to.</li> </ul>  
 *
 * OpenAPI spec version: 10.0
 * Contact: support@quickpay.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing QuickPayProtocolV10AcquirerSettingsClearhaus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class QuickPayProtocolV10AcquirerSettingsClearhausTests
    {
        // TODO uncomment below to declare an instance variable for QuickPayProtocolV10AcquirerSettingsClearhaus
        //private QuickPayProtocolV10AcquirerSettingsClearhaus instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of QuickPayProtocolV10AcquirerSettingsClearhaus
            //instance = new QuickPayProtocolV10AcquirerSettingsClearhaus();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of QuickPayProtocolV10AcquirerSettingsClearhaus
        /// </summary>
        [Test]
        public void QuickPayProtocolV10AcquirerSettingsClearhausInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" QuickPayProtocolV10AcquirerSettingsClearhaus
            //Assert.IsInstanceOfType<QuickPayProtocolV10AcquirerSettingsClearhaus> (instance, "variable 'instance' is a QuickPayProtocolV10AcquirerSettingsClearhaus");
        }


        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Test]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }
        /// <summary>
        /// Test the property 'ApiKey'
        /// </summary>
        [Test]
        public void ApiKeyTest()
        {
            // TODO unit test for the property 'ApiKey'
        }
        /// <summary>
        /// Test the property 'ApplePay'
        /// </summary>
        [Test]
        public void ApplePayTest()
        {
            // TODO unit test for the property 'ApplePay'
        }
        /// <summary>
        /// Test the property 'BusinessCode'
        /// </summary>
        [Test]
        public void BusinessCodeTest()
        {
            // TODO unit test for the property 'BusinessCode'
        }
        /// <summary>
        /// Test the property 'MpiMerchantId'
        /// </summary>
        [Test]
        public void MpiMerchantIdTest()
        {
            // TODO unit test for the property 'MpiMerchantId'
        }
        /// <summary>
        /// Test the property 'Payout'
        /// </summary>
        [Test]
        public void PayoutTest()
        {
            // TODO unit test for the property 'Payout'
        }
        /// <summary>
        /// Test the property 'Recurring'
        /// </summary>
        [Test]
        public void RecurringTest()
        {
            // TODO unit test for the property 'Recurring'
        }

    }

}
