/* 
 * Quickpay API v10
 *
 * <h2 id=\"authorization\">Authorization</h2>  <p>Authorization is done using basic-auth. Authorization can be done with a user or an agreement.</p>  <ul>   <li>When authorized with a user one is able to edit own settings, create new merchant or request access to existing merchant.</li>   <li>When authorized with an agreement one is able to perform anything on the account that agreement gives permissions to.</li> </ul>  
 *
 * OpenAPI spec version: 10.0
 * Contact: support@quickpay.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing QuickPayProtocolV10AcquirerTestDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class QuickPayProtocolV10AcquirerTestDetailsTests
    {
        // TODO uncomment below to declare an instance variable for QuickPayProtocolV10AcquirerTestDetails
        //private QuickPayProtocolV10AcquirerTestDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of QuickPayProtocolV10AcquirerTestDetails
            //instance = new QuickPayProtocolV10AcquirerTestDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of QuickPayProtocolV10AcquirerTestDetails
        /// </summary>
        [Test]
        public void QuickPayProtocolV10AcquirerTestDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" QuickPayProtocolV10AcquirerTestDetails
            //Assert.IsInstanceOfType<QuickPayProtocolV10AcquirerTestDetails> (instance, "variable 'instance' is a QuickPayProtocolV10AcquirerTestDetails");
        }


        /// <summary>
        /// Test the property '_3dSecure'
        /// </summary>
        [Test]
        public void _3dSecureTest()
        {
            // TODO unit test for the property '_3dSecure'
        }
        /// <summary>
        /// Test the property 'Dankort'
        /// </summary>
        [Test]
        public void DankortTest()
        {
            // TODO unit test for the property 'Dankort'
        }
        /// <summary>
        /// Test the property 'Diners'
        /// </summary>
        [Test]
        public void DinersTest()
        {
            // TODO unit test for the property 'Diners'
        }
        /// <summary>
        /// Test the property 'Fbg1886'
        /// </summary>
        [Test]
        public void Fbg1886Test()
        {
            // TODO unit test for the property 'Fbg1886'
        }
        /// <summary>
        /// Test the property 'Mastercard'
        /// </summary>
        [Test]
        public void MastercardTest()
        {
            // TODO unit test for the property 'Mastercard'
        }
        /// <summary>
        /// Test the property 'Recurring'
        /// </summary>
        [Test]
        public void RecurringTest()
        {
            // TODO unit test for the property 'Recurring'
        }
        /// <summary>
        /// Test the property 'Visa'
        /// </summary>
        [Test]
        public void VisaTest()
        {
            // TODO unit test for the property 'Visa'
        }

    }

}
