/* 
 * Quickpay API v10
 *
 * <h2 id=\"authorization\">Authorization</h2>  <p>Authorization is done using basic-auth. Authorization can be done with a user or an agreement.</p>  <ul>   <li>When authorized with a user one is able to edit own settings, create new merchant or request access to existing merchant.</li>   <li>When authorized with an agreement one is able to perform anything on the account that agreement gives permissions to.</li> </ul>  
 *
 * OpenAPI spec version: 10.0
 * Contact: support@quickpay.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing QuickPayProtocolV10AcquirerSettingsSofort
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class QuickPayProtocolV10AcquirerSettingsSofortTests
    {
        // TODO uncomment below to declare an instance variable for QuickPayProtocolV10AcquirerSettingsSofort
        //private QuickPayProtocolV10AcquirerSettingsSofort instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of QuickPayProtocolV10AcquirerSettingsSofort
            //instance = new QuickPayProtocolV10AcquirerSettingsSofort();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of QuickPayProtocolV10AcquirerSettingsSofort
        /// </summary>
        [Test]
        public void QuickPayProtocolV10AcquirerSettingsSofortInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" QuickPayProtocolV10AcquirerSettingsSofort
            //Assert.IsInstanceOfType<QuickPayProtocolV10AcquirerSettingsSofort> (instance, "variable 'instance' is a QuickPayProtocolV10AcquirerSettingsSofort");
        }


        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Test]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }
        /// <summary>
        /// Test the property 'ApiKey'
        /// </summary>
        [Test]
        public void ApiKeyTest()
        {
            // TODO unit test for the property 'ApiKey'
        }
        /// <summary>
        /// Test the property 'CustomerNumber'
        /// </summary>
        [Test]
        public void CustomerNumberTest()
        {
            // TODO unit test for the property 'CustomerNumber'
        }
        /// <summary>
        /// Test the property 'Gateway'
        /// </summary>
        [Test]
        public void GatewayTest()
        {
            // TODO unit test for the property 'Gateway'
        }
        /// <summary>
        /// Test the property 'Ideal'
        /// </summary>
        [Test]
        public void IdealTest()
        {
            // TODO unit test for the property 'Ideal'
        }
        /// <summary>
        /// Test the property 'IdealNotificationPassword'
        /// </summary>
        [Test]
        public void IdealNotificationPasswordTest()
        {
            // TODO unit test for the property 'IdealNotificationPassword'
        }
        /// <summary>
        /// Test the property 'IdealProjectId'
        /// </summary>
        [Test]
        public void IdealProjectIdTest()
        {
            // TODO unit test for the property 'IdealProjectId'
        }
        /// <summary>
        /// Test the property 'IdealProjectPassword'
        /// </summary>
        [Test]
        public void IdealProjectPasswordTest()
        {
            // TODO unit test for the property 'IdealProjectPassword'
        }
        /// <summary>
        /// Test the property 'ProjectId'
        /// </summary>
        [Test]
        public void ProjectIdTest()
        {
            // TODO unit test for the property 'ProjectId'
        }

    }

}
