/* 
 * Quickpay API v10
 *
 * <h2 id=\"authorization\">Authorization</h2>  <p>Authorization is done using basic-auth. Authorization can be done with a user or an agreement.</p>  <ul>   <li>When authorized with a user one is able to edit own settings, create new merchant or request access to existing merchant.</li>   <li>When authorized with an agreement one is able to perform anything on the account that agreement gives permissions to.</li> </ul>  
 *
 * OpenAPI spec version: 10.0
 * Contact: support@quickpay.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing QuickPayProtocolV10PaymentLink
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class QuickPayProtocolV10PaymentLinkTests
    {
        // TODO uncomment below to declare an instance variable for QuickPayProtocolV10PaymentLink
        //private QuickPayProtocolV10PaymentLink instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of QuickPayProtocolV10PaymentLink
            //instance = new QuickPayProtocolV10PaymentLink();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of QuickPayProtocolV10PaymentLink
        /// </summary>
        [Test]
        public void QuickPayProtocolV10PaymentLinkInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" QuickPayProtocolV10PaymentLink
            //Assert.IsInstanceOfType<QuickPayProtocolV10PaymentLink> (instance, "variable 'instance' is a QuickPayProtocolV10PaymentLink");
        }


        /// <summary>
        /// Test the property 'Acquirer'
        /// </summary>
        [Test]
        public void AcquirerTest()
        {
            // TODO unit test for the property 'Acquirer'
        }
        /// <summary>
        /// Test the property 'AgreementId'
        /// </summary>
        [Test]
        public void AgreementIdTest()
        {
            // TODO unit test for the property 'AgreementId'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Test]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'AutoCapture'
        /// </summary>
        [Test]
        public void AutoCaptureTest()
        {
            // TODO unit test for the property 'AutoCapture'
        }
        /// <summary>
        /// Test the property 'AutoFee'
        /// </summary>
        [Test]
        public void AutoFeeTest()
        {
            // TODO unit test for the property 'AutoFee'
        }
        /// <summary>
        /// Test the property 'BrandingConfig'
        /// </summary>
        [Test]
        public void BrandingConfigTest()
        {
            // TODO unit test for the property 'BrandingConfig'
        }
        /// <summary>
        /// Test the property 'BrandingId'
        /// </summary>
        [Test]
        public void BrandingIdTest()
        {
            // TODO unit test for the property 'BrandingId'
        }
        /// <summary>
        /// Test the property 'CallbackUrl'
        /// </summary>
        [Test]
        public void CallbackUrlTest()
        {
            // TODO unit test for the property 'CallbackUrl'
        }
        /// <summary>
        /// Test the property 'CancelUrl'
        /// </summary>
        [Test]
        public void CancelUrlTest()
        {
            // TODO unit test for the property 'CancelUrl'
        }
        /// <summary>
        /// Test the property 'ContinueUrl'
        /// </summary>
        [Test]
        public void ContinueUrlTest()
        {
            // TODO unit test for the property 'ContinueUrl'
        }
        /// <summary>
        /// Test the property 'CustomerEmail'
        /// </summary>
        [Test]
        public void CustomerEmailTest()
        {
            // TODO unit test for the property 'CustomerEmail'
        }
        /// <summary>
        /// Test the property 'Deadline'
        /// </summary>
        [Test]
        public void DeadlineTest()
        {
            // TODO unit test for the property 'Deadline'
        }
        /// <summary>
        /// Test the property 'Framed'
        /// </summary>
        [Test]
        public void FramedTest()
        {
            // TODO unit test for the property 'Framed'
        }
        /// <summary>
        /// Test the property 'GoogleAnalyticsClientId'
        /// </summary>
        [Test]
        public void GoogleAnalyticsClientIdTest()
        {
            // TODO unit test for the property 'GoogleAnalyticsClientId'
        }
        /// <summary>
        /// Test the property 'GoogleAnalyticsTrackingId'
        /// </summary>
        [Test]
        public void GoogleAnalyticsTrackingIdTest()
        {
            // TODO unit test for the property 'GoogleAnalyticsTrackingId'
        }
        /// <summary>
        /// Test the property 'InvoiceAddressSelection'
        /// </summary>
        [Test]
        public void InvoiceAddressSelectionTest()
        {
            // TODO unit test for the property 'InvoiceAddressSelection'
        }
        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Test]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }
        /// <summary>
        /// Test the property 'PaymentMethods'
        /// </summary>
        [Test]
        public void PaymentMethodsTest()
        {
            // TODO unit test for the property 'PaymentMethods'
        }
        /// <summary>
        /// Test the property 'ShippingAddressSelection'
        /// </summary>
        [Test]
        public void ShippingAddressSelectionTest()
        {
            // TODO unit test for the property 'ShippingAddressSelection'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }

    }

}
