/* 
 * Quickpay API v10
 *
 * <h2 id=\"authorization\">Authorization</h2>  Authorization is done using basic-auth. Authorization can be done with a user or an agreement.  <ul>   <li>When authorized with a user one is able to edit own settings, create new merchant or request access to existing merchant.</li>   <li>When authorized with an agreement one is able to perform anything on the account that agreement gives permissions to.</li> </ul>  
 *
 * OpenAPI spec version: 10.0
 * Contact: support@quickpay.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SubscriptionsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class SubscriptionsApiTests
    {
        private SubscriptionsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new SubscriptionsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SubscriptionsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' SubscriptionsApi
            //Assert.IsInstanceOfType(typeof(SubscriptionsApi), instance, "instance is a SubscriptionsApi");
        }

        
        /// <summary>
        /// Test DELETESubscriptionsIdLinkFormat
        /// </summary>
        [Test]
        public void DELETESubscriptionsIdLinkFormatTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string acceptVersion = null;
            //string authorization = null;
            //int? id = null;
            //instance.DELETESubscriptionsIdLinkFormat(acceptVersion, authorization, id);
            
        }
        
        /// <summary>
        /// Test GETSubscriptionsFormat
        /// </summary>
        [Test]
        public void GETSubscriptionsFormatTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string acceptVersion = null;
            //string authorization = null;
            //int? dateYear = null;
            //int? dateMonth = null;
            //int? dateDay = null;
            //int? dateHour = null;
            //int? dateMinute = null;
            //string timestamp = null;
            //string minTime = null;
            //string maxTime = null;
            //int? operationsSize = null;
            //bool? accepted = null;
            //string orderId = null;
            //string state = null;
            //int? id = null;
            //string acquirer = null;
            //int? groupId = null;
            //bool? fraudSuspected = null;
            //bool? expired = null;
            //int? page = null;
            //int? pageSize = null;
            //string sortBy = null;
            //string sortDir = null;
            //string pageKey = null;
            //var response = instance.GETSubscriptionsFormat(acceptVersion, authorization, dateYear, dateMonth, dateDay, dateHour, dateMinute, timestamp, minTime, maxTime, operationsSize, accepted, orderId, state, id, acquirer, groupId, fraudSuspected, expired, page, pageSize, sortBy, sortDir, pageKey);
            //Assert.IsInstanceOf<Subscription> (response, "response is Subscription");
        }
        
        /// <summary>
        /// Test GETSubscriptionsIdFormat
        /// </summary>
        [Test]
        public void GETSubscriptionsIdFormatTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string acceptVersion = null;
            //string authorization = null;
            //int? id = null;
            //int? operationsSize = null;
            //var response = instance.GETSubscriptionsIdFormat(acceptVersion, authorization, id, operationsSize);
            //Assert.IsInstanceOf<Subscription> (response, "response is Subscription");
        }
        
        /// <summary>
        /// Test GETSubscriptionsIdOperationsOperationIdFormat
        /// </summary>
        [Test]
        public void GETSubscriptionsIdOperationsOperationIdFormatTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string acceptVersion = null;
            //string authorization = null;
            //int? id = null;
            //int? operationId = null;
            //var response = instance.GETSubscriptionsIdOperationsOperationIdFormat(acceptVersion, authorization, id, operationId);
            //Assert.IsInstanceOf<Operation> (response, "response is Operation");
        }
        
        /// <summary>
        /// Test GETSubscriptionsIdPaymentsFormat
        /// </summary>
        [Test]
        public void GETSubscriptionsIdPaymentsFormatTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string acceptVersion = null;
            //string authorization = null;
            //int? id = null;
            //bool? accepted = null;
            //int? dateYear = null;
            //int? dateMonth = null;
            //int? dateDay = null;
            //int? dateHour = null;
            //int? dateMinute = null;
            //int? page = null;
            //int? pageSize = null;
            //string sortBy = null;
            //string sortDir = null;
            //var response = instance.GETSubscriptionsIdPaymentsFormat(acceptVersion, authorization, id, accepted, dateYear, dateMonth, dateDay, dateHour, dateMinute, page, pageSize, sortBy, sortDir);
            //Assert.IsInstanceOf<Payment> (response, "response is Payment");
        }
        
        /// <summary>
        /// Test PATCHSubscriptionsIdFormat
        /// </summary>
        [Test]
        public void PATCHSubscriptionsIdFormatTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string acceptVersion = null;
            //string authorization = null;
            //int? id = null;
            //DateTime? deadlineAt = null;
            //string groupIds = null;
            //string description = null;
            //string invoiceAddressName = null;
            //string invoiceAddressAtt = null;
            //string invoiceAddressCompanyName = null;
            //string invoiceAddressStreet = null;
            //string invoiceAddressHouseNumber = null;
            //string invoiceAddressHouseExtension = null;
            //string invoiceAddressCity = null;
            //string invoiceAddressZipCode = null;
            //string invoiceAddressRegion = null;
            //string invoiceAddressCountryCode = null;
            //string invoiceAddressVatNo = null;
            //string invoiceAddressPhoneNumber = null;
            //string invoiceAddressMobileNumber = null;
            //string invoiceAddressEmail = null;
            //string shippingAddressName = null;
            //string shippingAddressAtt = null;
            //string shippingAddressCompanyName = null;
            //string shippingAddressStreet = null;
            //string shippingAddressHouseNumber = null;
            //string shippingAddressHouseExtension = null;
            //string shippingAddressCity = null;
            //string shippingAddressZipCode = null;
            //string shippingAddressRegion = null;
            //string shippingAddressCountryCode = null;
            //string shippingAddressVatNo = null;
            //string shippingAddressPhoneNumber = null;
            //string shippingAddressMobileNumber = null;
            //string shippingAddressEmail = null;
            //string variables = null;
            //var response = instance.PATCHSubscriptionsIdFormat(acceptVersion, authorization, id, deadlineAt, groupIds, description, invoiceAddressName, invoiceAddressAtt, invoiceAddressCompanyName, invoiceAddressStreet, invoiceAddressHouseNumber, invoiceAddressHouseExtension, invoiceAddressCity, invoiceAddressZipCode, invoiceAddressRegion, invoiceAddressCountryCode, invoiceAddressVatNo, invoiceAddressPhoneNumber, invoiceAddressMobileNumber, invoiceAddressEmail, shippingAddressName, shippingAddressAtt, shippingAddressCompanyName, shippingAddressStreet, shippingAddressHouseNumber, shippingAddressHouseExtension, shippingAddressCity, shippingAddressZipCode, shippingAddressRegion, shippingAddressCountryCode, shippingAddressVatNo, shippingAddressPhoneNumber, shippingAddressMobileNumber, shippingAddressEmail, variables);
            //Assert.IsInstanceOf<Subscription> (response, "response is Subscription");
        }
        
        /// <summary>
        /// Test PATCHSubscriptionsIdOperationsOperationIdFormat
        /// </summary>
        [Test]
        public void PATCHSubscriptionsIdOperationsOperationIdFormatTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string acceptVersion = null;
            //string authorization = null;
            //int? id = null;
            //int? operationId = null;
            //bool? pending = null;
            //var response = instance.PATCHSubscriptionsIdOperationsOperationIdFormat(acceptVersion, authorization, id, operationId, pending);
            //Assert.IsInstanceOf<Operation> (response, "response is Operation");
        }
        
        /// <summary>
        /// Test POSTSubscriptionsFormat
        /// </summary>
        [Test]
        public void POSTSubscriptionsFormatTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string acceptVersion = null;
            //string authorization = null;
            //string orderId = null;
            //string currency = null;
            //string description = null;
            //string invoiceAddressName = null;
            //string invoiceAddressAtt = null;
            //string invoiceAddressCompanyName = null;
            //string invoiceAddressStreet = null;
            //string invoiceAddressHouseNumber = null;
            //string invoiceAddressHouseExtension = null;
            //string invoiceAddressCity = null;
            //string invoiceAddressZipCode = null;
            //string invoiceAddressRegion = null;
            //string invoiceAddressCountryCode = null;
            //string invoiceAddressVatNo = null;
            //string invoiceAddressPhoneNumber = null;
            //string invoiceAddressMobileNumber = null;
            //string invoiceAddressEmail = null;
            //string shippingAddressName = null;
            //string shippingAddressAtt = null;
            //string shippingAddressCompanyName = null;
            //string shippingAddressStreet = null;
            //string shippingAddressHouseNumber = null;
            //string shippingAddressHouseExtension = null;
            //string shippingAddressCity = null;
            //string shippingAddressZipCode = null;
            //string shippingAddressRegion = null;
            //string shippingAddressCountryCode = null;
            //string shippingAddressVatNo = null;
            //string shippingAddressPhoneNumber = null;
            //string shippingAddressMobileNumber = null;
            //string shippingAddressEmail = null;
            //string variables = null;
            //int? brandingId = null;
            //string groupIds = null;
            //string textOnStatement = null;
            //string shopsystemName = null;
            //string shopsystemVersion = null;
            //var response = instance.POSTSubscriptionsFormat(acceptVersion, authorization, orderId, currency, description, invoiceAddressName, invoiceAddressAtt, invoiceAddressCompanyName, invoiceAddressStreet, invoiceAddressHouseNumber, invoiceAddressHouseExtension, invoiceAddressCity, invoiceAddressZipCode, invoiceAddressRegion, invoiceAddressCountryCode, invoiceAddressVatNo, invoiceAddressPhoneNumber, invoiceAddressMobileNumber, invoiceAddressEmail, shippingAddressName, shippingAddressAtt, shippingAddressCompanyName, shippingAddressStreet, shippingAddressHouseNumber, shippingAddressHouseExtension, shippingAddressCity, shippingAddressZipCode, shippingAddressRegion, shippingAddressCountryCode, shippingAddressVatNo, shippingAddressPhoneNumber, shippingAddressMobileNumber, shippingAddressEmail, variables, brandingId, groupIds, textOnStatement, shopsystemName, shopsystemVersion);
            //Assert.IsInstanceOf<Subscription> (response, "response is Subscription");
        }
        
        /// <summary>
        /// Test POSTSubscriptionsIdAuthorizeFormat
        /// </summary>
        [Test]
        public void POSTSubscriptionsIdAuthorizeFormatTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string acceptVersion = null;
            //string authorization = null;
            //int? id = null;
            //int? amount = null;
            //string quickPayCallbackUrl = null;
            //bool? synchronized = null;
            //float? vatRate = null;
            //string cardNumber = null;
            //string cardExpiration = null;
            //string cardCvd = null;
            //string cardToken = null;
            //string cardApplePayToken = null;
            //string cardMobilepayOnlineToken = null;
            //string cardIssuedTo = null;
            //string cardBrand = null;
            //string cardStatus = null;
            //string cardEci = null;
            //string cardXav = null;
            //string cardCavv = null;
            //string mobileNumber = null;
            //string ninNumber = null;
            //string ninCountryCode = null;
            //string ninGender = null;
            //string personFirstName = null;
            //string personLastName = null;
            //string personEmail = null;
            //string acquirer = null;
            //string customerIp = null;
            //string extras = null;
            //var response = instance.POSTSubscriptionsIdAuthorizeFormat(acceptVersion, authorization, id, amount, quickPayCallbackUrl, synchronized, vatRate, cardNumber, cardExpiration, cardCvd, cardToken, cardApplePayToken, cardMobilepayOnlineToken, cardIssuedTo, cardBrand, cardStatus, cardEci, cardXav, cardCavv, mobileNumber, ninNumber, ninCountryCode, ninGender, personFirstName, personLastName, personEmail, acquirer, customerIp, extras);
            //Assert.IsInstanceOf<Subscription> (response, "response is Subscription");
        }
        
        /// <summary>
        /// Test POSTSubscriptionsIdCancelFormat
        /// </summary>
        [Test]
        public void POSTSubscriptionsIdCancelFormatTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string acceptVersion = null;
            //string authorization = null;
            //int? id = null;
            //string quickPayCallbackUrl = null;
            //bool? synchronized = null;
            //var response = instance.POSTSubscriptionsIdCancelFormat(acceptVersion, authorization, id, quickPayCallbackUrl, synchronized);
            //Assert.IsInstanceOf<Subscription> (response, "response is Subscription");
        }
        
        /// <summary>
        /// Test POSTSubscriptionsIdFraudReportFormat
        /// </summary>
        [Test]
        public void POSTSubscriptionsIdFraudReportFormatTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string acceptVersion = null;
            //string authorization = null;
            //int? id = null;
            //string quickPayCallbackUrl = null;
            //string description = null;
            //var response = instance.POSTSubscriptionsIdFraudReportFormat(acceptVersion, authorization, id, quickPayCallbackUrl, description);
            //Assert.IsInstanceOf<FraudReport> (response, "response is FraudReport");
        }
        
        /// <summary>
        /// Test POSTSubscriptionsIdRecurringFormat
        /// </summary>
        [Test]
        public void POSTSubscriptionsIdRecurringFormatTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string acceptVersion = null;
            //string authorization = null;
            //int? id = null;
            //int? amount = null;
            //string orderId = null;
            //string quickPayCallbackUrl = null;
            //bool? synchronized = null;
            //bool? autoCapture = null;
            //bool? autofee = null;
            //bool? zeroAuth = null;
            //string textOnStatement = null;
            //var response = instance.POSTSubscriptionsIdRecurringFormat(acceptVersion, authorization, id, amount, orderId, quickPayCallbackUrl, synchronized, autoCapture, autofee, zeroAuth, textOnStatement);
            //Assert.IsInstanceOf<Payment> (response, "response is Payment");
        }
        
        /// <summary>
        /// Test POSTSubscriptionsIdSessionFormat
        /// </summary>
        [Test]
        public void POSTSubscriptionsIdSessionFormatTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string acceptVersion = null;
            //string authorization = null;
            //int? id = null;
            //string quickPayCallbackUrl = null;
            //string acquirer = null;
            //bool? autofee = null;
            //string customerIp = null;
            //string extras = null;
            //var response = instance.POSTSubscriptionsIdSessionFormat(acceptVersion, authorization, id, quickPayCallbackUrl, acquirer, autofee, customerIp, extras);
            //Assert.IsInstanceOf<Subscription> (response, "response is Subscription");
        }
        
        /// <summary>
        /// Test PUTSubscriptionsIdLinkFormat
        /// </summary>
        [Test]
        public void PUTSubscriptionsIdLinkFormatTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string acceptVersion = null;
            //string authorization = null;
            //int? id = null;
            //int? amount = null;
            //int? agreementId = null;
            //string language = null;
            //string continueUrl = null;
            //string cancelUrl = null;
            //string callbackUrl = null;
            //string paymentMethods = null;
            //bool? autoFee = null;
            //int? brandingId = null;
            //string googleAnalyticsTrackingId = null;
            //string googleAnalyticsClientId = null;
            //string acquirer = null;
            //int? deadline = null;
            //bool? framed = null;
            //string brandingConfig = null;
            //string customerEmail = null;
            //bool? invoiceAddressSelection = null;
            //bool? shippingAddressSelection = null;
            //var response = instance.PUTSubscriptionsIdLinkFormat(acceptVersion, authorization, id, amount, agreementId, language, continueUrl, cancelUrl, callbackUrl, paymentMethods, autoFee, brandingId, googleAnalyticsTrackingId, googleAnalyticsClientId, acquirer, deadline, framed, brandingConfig, customerEmail, invoiceAddressSelection, shippingAddressSelection);
            //Assert.IsInstanceOf<PaymentLinkUrl> (response, "response is PaymentLinkUrl");
        }
        
    }

}
